<a href="https://colab.research.google.com/github/tae-h-yang/cs224r/blob/main/CS_224R_PyTorch_Tutorial_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Author*: Marcel Torne

With inspiration from the previous CS224r tutorial by : Kyle Hsu with revisions from: Rafael Rafailov, Evan Liu, Fahim Tajwar, Annie Xie

And from the CS224n tutorial by: Dilara Soylu and Ethan Chi

Some installation requirements:

In [1]:
!pip install ipycanvas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.8/125.8 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.1 MB/s eta 0:00:00


# Introduction
Welcome to the PyTorch tutorial for CS 224R! This colab notebook accompanies [these slides](https://docs.google.com/presentation/d/1MC2XqjzN0M-R-Y-uMjefAqqEZRg7q2igFqAfu1P2_yo/edit?usp=sharing). If you haven't already, enable a GPU for this colab instance by doing "Edit" -> "Notebook settings" -> "Hardware accelerator" drop-down -> "GPU" -> "Save".

Let's make sure we're using the right Python and PyTorch versions, and that we have a GPU at our disposal.

In [2]:
import sys
import torch
import numpy as np
print(f'Python version info: {sys.version}')
print(f'PyTorch version info: {torch.__version__}')
print(f'PyTorch detects a GPU: {torch.cuda.is_available()}')

Python version info: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]
PyTorch version info: 2.6.0+cu124
PyTorch detects a GPU: True


# Overview
We'll begin looking at the very fundamentals of PyTorch, how to create and operate with tensors, and how to leverage your GPU to do your operations faster. Then we will go through the basics of PyTorch by looking into training an agent to train the custom made game for the class, the Stanford Flappybird.

I also added some additional details that we might go through if there's time or that you can go through on your own. These details include understanding better autograd by solving and ODE in PyTorch.

I hope all this information will be useful for your homeworks for this course but also for your professional career.

# Pytorch fundamentals

**Tensors** are PyTorch's most basic building block. Each tensor is a multi-dimensional matrix. The PyTorch library API is very similar to the numpy library.

Let's look into how to create a tensor:

In [3]:
# 1. Create a tensor from a list of lists
tensor_from_list = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Tensor from list of lists:\n", tensor_from_list)

# 2. Create a tensor from a numpy array
np_array = np.array([[1.0, 2.0], [3.0, 4.0]])
tensor_from_numpy = torch.from_numpy(np_array)
print("\nTensor from numpy: \n", tensor_from_numpy)

# 3. Create a tensor using the PyTorch library
random_tensor = torch.randn(2, 3)  # 2x3 tensor with random values from a normal distribution
zeros_tensor = torch.zeros(2, 6) # 2x6 tensor with zeros
print("\nRandom tensor:\n", random_tensor)
print("\nZeros tensor:\n", zeros_tensor)


Tensor from list of lists:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor from numpy: 
 tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Random tensor:
 tensor([[ 0.3312, -0.0648, -1.4522],
        [-0.2675, -1.0010, -1.6582]])

Zeros tensor:
 tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


array([[1., 2.],
       [3., 4.]])